# Generated by Django 5.1 on 2024-08-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('salesRep', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=200)),
                ('creationDate', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(max_length=20)),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('estimatedValue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estimatedCloseDate', models.DateField(blank=True, null=True)),
                ('contractValue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('contractDate', models.DateField(blank=True, null=True)),
                ('total_received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'projects_project',
                'unique_together': {('code',)},
            },
        ),
    ]
